version: "3" 
services:
    nginx:
        build:
            context: ./docker-nginx/
        container_name: nginx
        depends_on:
            - ask
        networks:
            - webnet
        ports:
            - "80:80"
    ask:
        build:
            context: ./flask-ask/
        container_name: ask
        depends_on:
            - pydocs
        networks:
            webnet:
                aliases:
                    - ask
    pydocs:
        build:
            context: ./flask-pydocs/
        container_name: pydocs
        networks:
            webnet:
                aliases:
                    - pydocs
        depends_on:
            - redis
    redis:
        image: redis
        container_name: redis
        ports:
          - "6379:6379"
            #        deploy:
            #          placement:
            #            constraints: [node.role == manager]
        command: redis-server --appendonly yes
        networks:
          - webnet
networks:
    webnet:
